# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container to Azure Web App - NodejsWebAppTest1

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write   # lets azure/login request the OIDC token
  contents: read    # lets actions/checkout read the repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: indev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F6E927284C074218B784132503D7B685 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5D72E9DDCF94D83AC2E956DF7162CD7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83E3CE6429CF4790A1563F7ECF095A86 }}

      - name: Log in to Azure ACR
        run: az acr login --name conveyacrtest

      - name: Build and push the image
        run: |
          docker build -t conveyacrtest.azurecr.io/nodejsworker:indev-${{ github.sha }} .
          docker push conveyacrtest.azurecr.io/nodejsworker:indev-${{ github.sha }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NodejsWebAppTest1'
          images: 'conveyacrtest.azurecr.io/nodejsworker:indev-${{ github.sha }}'
          slot-name: 'production'